version: 2

sources:
  - name: olist
    schema: dev_raw
    tables:
      - name: order
      - name: order_item
      - name: customer
      - name: product
      - name: seller
      - name: payment
      - name: review