version: 2

sources:
  - name: olist
    schema: dev_raw
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: products
      - name: sellers
      - name: payments
      - name: reviews
      - name: geolocation