olist_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: <host_name>
      user: <username>
      password: <password>
      port: <port>
      dbname: <database_name>
      schema: <schema_name>
      threads: 10
